### ISSUE TITLE
Restore health and mana on level up

### ISSUE THREAD

**Issue by nok1111** [GustavoContreiras/TheForgottenTibia#1]
players wont get their mana/hp back on level up

**Comment by GustavoContreiras** [comment]
This is not a issue. I disabled it.
But I'm gonna enable as soon as I can and make it a config.lua option.

**Comment by GustavoContreiras** [comment]
Done.

Added option to refill (or not) HP and MP on level up (https://github.com/GustavoContreiras/TheForgottenTibia/commit/624a49678535b1faee2dd1e462f105adc2a5303f)
