### ISSUE TITLE
kinda new

### ISSUE THREAD

**Issue by feister04** [GustavoContreiras/TheForgottenTibia#10]
Hello, im kinda new to all of the newer stuff.  I have made a server in the past but never hosted it, more created a server for just me and my friends and was planning on doing the same again when i seen this.  this is what ive been getting,
 	Error: Apache shutdown unexpectedly.
10:40:15 PM  [Apache] 	This may be due to a blocked port, missing dependencies, 
10:40:15 PM  [Apache] 	improper privileges, a crash, or a shutdown by another method.
10:40:15 PM  [Apache] 	Press the Logs button to view error logs and check
10:40:15 PM  [Apache] 	the Windows Event Viewer for more clues
10:40:15 PM  [Apache] 	If you need more help, copy and post this
10:40:15 PM  [Apache] 	entire log window on the forums

and the other question i have is how do you create a new database on xampp? and when i try to run the server it just auto closes it within seconds.   Thank you

**Comment by GustavoContreiras** [comment]
These kind of doubts are not related to the project.

To solve that you should take a look at these links:
https://docs.otland.net/ots-guide/running-your-first-ot-server/setting-up-your-first-server
https://otland.net/

And I wouldn't recommend you to use my project until you can run the official TheForgottenServer without problems.
