### ISSUE TITLE
Double skill points when leveling repeated level

### ISSUE THREAD

**Issue by dniloms** [GustavoContreiras/TheForgottenTibia#12]
Ao morrer e voltar o level, os pontos de skill continuam iguais. E ao upar o level novamente, você ganha os mesmos pontos novamente, acumulando com os antigos.

Ou seja, se eu ganho **4** pontos de skill do level 30 para o 31.  E por acaso eu volto do lvl 31 para o lvl 30. Quando eu upar para o lvl 31 novamente, eu terei **8** pontos para distribuir no total.

**Comment by GustavoContreiras** [comment]
I'm not working anymore on the project but if someone want to fix the answer might be here https://github.com/GustavoContreiras/TheForgottenTibia/issues/11

It's not so hard to fix

**Comment by GustavoContreiras** [comment]
Fix with commit https://github.com/GustavoContreiras/TheForgottenTibia/commit/fffe88a5849031d4342a6dec704cc5fe4cea2d81
