### ISSUE TITLE
stats refresh on skill/conditions spells

### ISSUE THREAD

**Issue by nok1111** [GustavoContreiras/TheForgottenTibia#16]
stats no longer refresh on client side after using spells/conditions that add extra skill parameters
as blood_rage and any other skill skill oriented.

example
condition:setParameter(CONDITION_PARAM_SKILL_DEXTERITY, 50)
server side working fine, client side not.
the numbers turn green but the numbers wont go up.

this is a bug with the latest updates

**Comment by GustavoContreiras** [comment]
I'm almost sure it was this piece of code here (the comment):
https://github.com/GustavoContreiras/TheForgottenTibia/blob/master/Server/src/weapons.cpp#L371

I had to comment it to make critical work on sources, but now lua scripts of weapons folder dont work and so dont add condition I think.

**Comment by nok1111** [comment]
I think this will solve it 👍  need to test it
https://github.com/GustavoContreiras/TheForgottenTibia/commit/408f8ba4868c5969004c824033114e5994dc995b
